### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by mwamp** [RobotWebTools/rclnodejs#470]
Hi,

I just want to report that using ros2_web_bridge saturates one CPU thread on my machine.
The likely issue is that processing power is never yielded as it should and some routines are constantly nagging to check for some event.

Here is a perf report, I produced this with very few topics; actions and services running.

  31.44%  node     libpthread-2.23.so    [.] pthread_mutex_lock
  27.91%  node     rclnodejs.node         [.] _ZN9rclnodejs8Executor3RunEPv
  20.04%  node     libpthread-2.23.so    [.] pthread_mutex_unlock
   4.46%  node     node                          [.] uv_mutex_unlock
   4.33%  node     node                          [.] uv_mutex_lock
   3.72%  node     rclnodejs.node           [.] uv_mutex_unlock@plt
   3.30%  node     rclnodejs.node           [.] uv_mutex_lock@plt
   2.31%  node     node                  [.] 0x00000000004b5b90
   2.24%  node     node                  [.] 0x00000000004b5be0

One question, is rclnodejs a wrapper on rclcpp or was is built from scratch. Wouldn't using swig or the like provide a suitable enough wrapper and easy to maintain?

**Comment by minggangw** [comment]
Thanks for submitting the issue, I'd like to answer them:

>The likely issue is that processing power is never yielded as it should and some routines are >constantly nagging to check for some event.

For the unreasonable CPU usage, it should be caused by frequent calling of uv_mutex_lock/uv_mutex_unlock. The reason why it happens is that we set a fixed timeout for [rcl_wait](https://github.com/RobotWebTools/rclnodejs/blob/develop/src/executor.cpp#L132) currently. This parameter should be customized.

>One question, is rclnodejs a wrapper on rclcpp or was is built from scratch. 

No, rclnodejs is not based on rclcpp, actually all clients of ROS2, including C++, Python and Node.js are based on [rcl](https://github.com/ros2/rcl) which is a C library, not platform related. You could consider rclnodejs is kind of wrapper, meanwhile, implement some platform specific features, like thread.

>Wouldn't using swig or the like provide a suitable enough wrapper and easy to maintain?

I'm not familiar with swig, not sure it can meet the requirement to implement the functions.

Finally, you are welcome to fix any problem you found, thanks again!

**Comment by minggangw** [comment]
This is a little late to come, but we did it finally. If you are still using it, please have a try to see if the performance changes. Thanks a lot!

**Comment by mwamp** [comment]
Great, I'll check it out as soon as I possible. 
Thanks a lot.

**Comment by mwamp** [comment]
Hi,
Unfortunately, I am unable to run tests right now. I am hit with a segfault (the very dark, no exception raised kind) as soon as rclnodejs is launched (in the basic service example for instance).

I am running dashing so maybe the reason is that I would need the nightly ros build?

**Comment by minggangw** [comment]
I didn't verify it on Dashing actually, as the code on `develop` branch will be tested on CIs by running unit tests. So I am going to double check it on the Dashing release. Thanks for your feedback.

**Comment by mwamp** [comment]
Actually, it looks like there are issues with NodeJS on my side, there shouldn't be anything wrong with this code.

**Comment by minggangw** [comment]
My previous description is not clear, I mean the `develop` branch of rclnodejs will be tested on the nightly ROS2 package through travis-ci. The Node.js version is the latest stable release usually.
